name: HousePurchase
version: '${version}'
main: fr.spectr2155e.housepurchase.HousePurchase
depend:
  - Essentials
  - Vault
commands:
  housepurchase:
    aliases: house, houses
    description: Commandes de HousePurchase
